spring:
  output:
    ansi:
      enabled: ALWAYS

  servlet:
    multipart:
      max-file-size: 10MB # 파일 하나 당 최대 사이즈
      max-request-size: 50MB # 요청 당 최대 사이즈

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://{JDBC_URL:PORT}/{DATABASE_NAME}?serverTimezone=Asia/Seoul
    username: {JDBC_USERNAME}
    password: {JDBC_PASSWORD}

  config:
   use-legacy-processing: true

  jpa:
   hibernate:
     ddl-auto: create
   show-sql: true
   properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        color-codes: true
        use_sql_comments: true
        type:
          descriptor:
            sql: trace

  security:
    oauth2:
      client:
        registration:
          google:
            clientId: {GOOGLE_CLIENT_ID}
            clientSecret: {GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
          kakao:
            client-id: {KAKAO_CLIENT_ID}
            client-secret: {KAKAO_CLIENT_SECRET}
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Kakao
            scope:
              - profile_nickname
              - account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

mail:
  address:
   admin: admin@gmail.com

jwt:
  key: ${JWT_SECRET_KEY}
  access-token-expiration-minutes: ${JWT_ACCESS_EXPIRATION_MINUTE}
  refresh-token-expiration-minutes: ${JWT_REFRESH_EXPIRATION_MINUTE}

cloud:
  aws:
    s3:
      bucket:
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      access-key: {AWS_ACCESSKEY}
      secret-key: {AWS_SECRETKEY}

cors:
  origins: http://localhost:3000
  methods: GET, POST, PATCH, DELETE
  headers: Authorization, Content-Type, X-Auth-Token
  exposedHeaders: X-Auth-Token, Authorization, MemberId